repos:
-   repo: local
    hooks:
    -   id: ruff-linter
        name: ruff-linter
        description: run ruff linter from local repo
        entry: env -i PATH=./bin:./.venv/bin:./venv/bin python3 -m ruff check . --fix --config pyproject.toml
        language: python
        types_or: [python]
        require_serial: true

    -   id: ruff-formatter
        name: ruff-formatter
        description: run ruff formatter from local repo
        entry: env -i PATH=./bin:./.venv/bin:./venv/bin python3 -m ruff format . --config pyproject.toml
        language: python
        types_or: [python]
        require_serial: true

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        description: run mypy from local repo
        entry: env -i PATH=./bin:./.venv/bin:./venv/bin python3 -m mypy
        args: [--config-file=./pyproject.toml]
        language: python
        types_or: [python]
        require_serial: true

-   repo: local
    hooks:
    -   id: pip-compile
        name: pip-compile
        description: run uv pip compile from local repo
        entry: make uv-compile
        language: python
        types_or: []
        require_serial: true
